library(shiny)
library(shinydashboard)
library(shinyWidgets)

todays_date <- as.Date(Sys.Date())

#read the csv files
hos <- read.csv("Res_CombiOR.hos.csv") 
poc<- read.csv ("Res_CombiOR.poc.csv")
HosProb<- read.csv("Res_HosProb.csv")

#split the files into risk factors and results
hos_rows<- hos[c(1,2,3,4,5,6,7,8,9,10)]
hos_results<-hos[c(11,12,13)]

prob_rows<- HosProb[c(1,2,3,4,5,6,7,8,9,10)]
prob_results<-HosProb[c(11,12,13)]

poc_rows<- poc[c(1,2,3)]
poc_results<-poc[c(4,5,6)]


#used navbarPage function instead of 2 different shiny apps for ease in server hosting 
ui<-navbarPage("", #This is needed for the layout to function 
               tags$img(src = "NJMU-1.png", height = "40px", width = "140px", style = "position:absolute;top:8px;left:15px;z-index:9999;"), #add logo and adjust size and position
               tags$head(
                 tags$style(type="text/css", "label{  display: table-cell; text-align: left; } .form-group { display: table; } #resultsheader{
                                 font-size: 16px;} #preventionheader{font-size: 16px;} #resultsheader2{font-size: 16px;} #preventionheader2{font-size: 16px;} 
                                 .navbar .navbar-nav {float: right}
                                 .navbar .navbar-header {float: right}
                                 
                                 .navbar-default { background-color: #FFFFFF!important;}
                            ")
               ),
  tabPanel("English (英语)",
    fluidRow(box(width =12, title="RSV RISK PREDICTION", solidHeader = TRUE, br(),
                 tags$p(tags$b("[Instructions for use]"), br(),"Respiratory syncytial virus (RSV) is the most common pathogen identified in children under five years with acute lower respiratory infections (ALRI), accounting for about 30% of all respiratory pathogens and affecting children's health. The risk for hospitalisation with RSV-ALRI and poor outcomes after hospitalisation differs by individual. This tool, developed by a research team from Nanjing Medical University, aims to predict the risks associated with RSV-ALRI in children under five years in China.",br(),
                        "Please enter child’s information below. Based on the provided information, the tool can predict: ",br(),"1. The risk of hospitalisation for RSV-ALRI for the child;", br(), "2. The probability of hospitalisation for RSV-ALRI of the child within the next year;  ", br(), "3. The risk of poor outcomes (need for prolonged hospital stay, oxygen supplementation, mechanical ventilation, or ICU admission) after being hospitalisated for RSV-ALRI.",style = "font-size:16px;",br(),br() ))),
    fluidRow(
      
      box(width =12, tags$b("[Child's personal information]", style = "font-size:16px;"), br(),br(),
          #This is to make the values in line with the csv file. 1 means it is positive for risk factor, 0 means negative
          prettyRadioButtons("sex", "1. Sex: ", choices= list("  Male"=1,"  Female"=0), selected = 0, shape = "square", inline=T), 
          dateInput("dob", "2. Date of Birth:", width = "320px"), #need to figure out how to make this look better
          prettyRadioButtons("siblings", "3. Number of siblings (defined as those living together with the child):", choices= list("0"= 0, "1"=1, "≥2"=2), selected = 0, shape="square", inline=T),
          numericInput("weight", "4. Birthweight (kg):", value=0, min=0, max=20),
          prettyRadioButtons("prematurity", "5. Prematurity (i.e., gestational age < 37 weeks):", choices = list("Yes"=1, "No"=0), selected = 0, shape="square", inline= T),
          prettyRadioButtons("BD", "6. Bronchopulmonary dysplasia:", choices = list("Yes"=1, "No"=0), selected = 0, shape="square", inline= T),
          prettyRadioButtons("down_syndrome", "7. Down syndrome:", choices = list("Yes"=1, "No"=0),selected = 0, shape="square", inline= T),
          prettyRadioButtons("chd", "8. Congenital heart disease:", choices = list("Yes"=1, "No"=0), selected = 0, shape="square", inline= T),
          prettyRadioButtons("hiv", "9. HIV infection:", choices = list("Yes"=1, "No"=0), selected = 0, shape="square", inline= T),
          prettyRadioButtons("smoking", "10. Maternal smoking during pregnancy:", choices = list("Yes"=1, "No"=0), selected = 0, shape="square", inline= T)
      )),
    
    fluidRow(box(actionButton("action", "Submit"))),
    
    fluidRow(box(width =12, br(), tags$p( 
      htmlOutput("resultsheader"),br(),
      textOutput("res_combiOR.hos"), br(),
      textOutput("Res_hosProb"), br(),
      textOutput("Res_CombiOR.poc"), br(),
      htmlOutput("preventionheader"),br(),
      textOutput("prevention"), br(),
      tags$b("[Disclaimer]", style = "font-size:16px;"),br(),
      "All information contained and generated by this tool is only used for health education. This information should not be used in the diagnosis or treatment for any health issues or diseases, nor should it in any way replace clinical judgment or guidance for the treatment of individual patients."
      
    )))
    
    
  ), 
  
  tabPanel("Chinese（中文）",
           fluidRow(box(width =12, title="呼吸道合胞病毒感染风险预测工具", solidHeader = TRUE, br(),
                        tags$p("呼吸道合胞病毒（RSV）是导致5岁以下儿童下呼吸道感染的最常见病原体，约占所有呼吸道病原体的30%，严重危害儿童健康。不同儿童RSV下呼吸道感染住院风险及住院后发生不良结局的风险存在一定差异。本工具由南京医科大学科研团队开发，可用于预测中国5岁以下儿童发生RSV下呼吸道感染的相关风险。",br(),
                               "请在下方输入儿童信息，本工具可以根据这些信息预测: ",br(),"1. 儿童RSV下呼吸道感染住院的风险", br(), "2. 儿童未来一年内RSV下呼吸道感染住院的可能性；  ", br(), "3. 儿童RSV下呼吸道感染住院后，发生不良结局（需要延长住院时间、吸氧、使用呼吸机或转入ICU）的风险。",style = "font-size:16px;",br(),br() ))),
           fluidRow(
             
             box(width =12, tags$b("【儿童基本信息】", style = "font-size:16px;"), br(),br(),
                 #This is to make the values in line with the csv file. 1 means it is positive for risk factor, 0 means negative
                 prettyRadioButtons("sex2", "1. 性别: ", choices= list("  男"=1,"  女"=0), selected = 0, shape = "square", inline=T), 
                 dateInput("dob2", "2. 出生日期:"), #need to figure out how to make this look better
                 prettyRadioButtons("siblings2", "3. 兄弟姐妹数量（共同居住，不含儿童本人）:", choices= list("0"= 0, "1"=1, "≥2"=2), selected = 0, shape="square", inline=T),
                 numericInput("weight2", "4. 出生体重 (公斤): ", value=0, min=0, max=20),
                 prettyRadioButtons("prematurity2", "5. 是否早产（指胎龄不满37周）:", choices = list("是"=1, "否"=0), selected = 0, shape="square", inline= T),
                 prettyRadioButtons("BD2", "6.是否患有支气管肺发育不良：", choices = list("是"=1, "否"=0), selected = 0, shape="square", inline= T),
                 prettyRadioButtons("down_syndrome2", "7. 是否患有唐氏综合症：", choices = list("是"=1, "否"=0),selected = 0, shape="square", inline= T),
                 prettyRadioButtons("chd2", "8. 是否患有先天性心脏病：", choices = list("是"=1, "否"=0), selected = 0, shape="square", inline= T),
                 prettyRadioButtons("hiv2", "9. 是否感染艾滋病病毒: ", choices = list("是"=1, "否"=0), selected = 0, shape="square", inline= T),
                 prettyRadioButtons("smoking2", "10. 母亲孕期是否吸烟：", choices = list("是"=1, "否"=0), selected = 0, shape="square", inline= T)
             )),
           
           fluidRow(box(actionButton("action2", "提交"))),
           #textOutput("selected_var"),
           
           fluidRow(box(width =12, br(), tags$p( 
             htmlOutput("resultsheader2"),br(),
             textOutput("res_combiOR.hos2"), br(),
             textOutput("Res_hosProb2"), br(),
             textOutput("Res_CombiOR.poc2"), br(),
             htmlOutput("preventionheader2"),br(),
             textOutput("prevention2"), br(),
             tags$b("【免责声明】", style = "font-size:16px;"),br(),
             "本工具所包含和生成的所有信息仅用于健康教育目的。这些信息不应被用于任何健康问题或疾病的诊断或治疗，也不能以任何方式取代临床判断或指导个体患者的治疗。"
             
           )))
          
          
  ))

#The server code needs to be copied twice - once for the English version and once for the Chinese version
server = function(input, output) {
  #English version =============================================================================================
  output$res_combiOR.hos <- renderText({
    #creates the 2 seperate variables from the siblings radio button
    req(input$action)
    siblings2<-0
    siblings1<-0
    if (isolate(input$siblings) == 2){
      siblings2<-1}
    else if (isolate(input$siblings)==1){
      siblings1<-1}
    #calculates risk factor based on birth weight
    if (isolate(input$weight)<2.5){
      weight<-1
    } else {weight <-0}
    masterlist<- isolate(c(siblings2, siblings1, input$BD, weight, input$down_syndrome,input$prematurity, input$chd, input$hiv, input$sex, input$smoking))
    #under here match the masterlist to the row of the csv. Use the code in calculations.R
    row<-which(colSums(t(hos_rows) == masterlist) == ncol(hos_rows))
    hosest<- hos_results[row, "est"]
    isolate(paste(" 1. The risk of hospitalisation for RSV-ALRI for the child would be ", round(hosest, digits=2), "times that of his/ her peers."))
    
  })
  
  output$Res_hosProb<- renderText({
    #copy the code from output$res_combiOR.hos
    req(input$action)
    siblings2<-0
    siblings1<-0
    if (isolate(input$siblings) == 2){
      siblings2<-1}
    else if (isolate(input$siblings)==1){
      siblings1<-1}
    if (isolate(input$weight)<2.5){
      weight<-1
    } else {weight <-0}
    masterlist<- isolate(c(siblings2, siblings1, input$BD, weight, input$down_syndrome,input$prematurity, input$chd, input$hiv, input$sex, input$smoking))
    row<-which(colSums(t(prob_rows) == masterlist) == ncol(prob_rows))
    probest<- prob_results[row, "est"]
    probest<- probest*100
    isolate(paste("2. The probability of hospitalisation for RSV-ALRI within the next year for the child would be  ", round(probest, digits = 2), "%"))
    
  })
  
  output$Res_CombiOR.poc<-renderText({
    req(input$action)
    #returns a list of the combination of the child's metrics, in line with the csv file
    calc_dob<-isolate(as.Date(input$dob))
    #calculates the difference in weeks between the child's dob and the current date
    diff_date<-difftime(todays_date, calc_dob, units= "weeks")
    diff_date <- as.numeric(diff_date)
    #6 months is 25 days 
    if (diff_date > 26){
      age<-0
    } else {age<-1}
    masterlist<-isolate(c(input$prematurity, input$chd, age))
    row<-isolate(which(colSums(t(poc_rows) == masterlist) == ncol(poc_rows)))
    pocest<- isolate(poc_results[row, "est"])
    
    isolate(paste("3. The risk of poor outcomes after being hospitalised for RSV-ALRI would be ", round(pocest, digits=2), "times that of his / her peers."))
    
  })
  
  output$resultsheader<-renderText({
    #just to check that the combination list is correct
    #return(selected_var())
    req(input$action)
    isolate(HTML(paste("<b>[Results]<b>")))
  })
  
  
  output$preventionheader<-renderText({
    #just to check that the combination list is correct
    #return(selected_var())
    req(input$action)
    isolate(HTML(paste("<b>[How to prevent RSV infection]<b>")))
  })
  
  
  
  output$prevention<-renderText({
    req(input$action)
    isolate(paste("To date, there are no vaccines for preventing RSV infection, and prophylactic monoclonal antibodies have not yet been marketed in China. Nonetheless, RSV infection can be effectively prevented by strengthening personal precautions, including avoiding visiting crowded places in winter and spring when RSV is most active and wearing masks at public venues; paying attention to hand hygiene, including washing hands frequently, and avoiding touching eyes, mouth, and nose with unwashed hands; and using personal protective equipment when attending hospitals to prevent hospital-acquired infections."))
  })
  
  #Chinese version ======================================================================================
  #all variables end with 2
  
  output$res_combiOR.hos2 <- renderText({
    #creates the 2 seperate variables from the siblings radio button
    req(input$action2)
    siblings22<-0
    siblings12<-0
    if (isolate(input$siblings2) == 2){
      siblings22<-1}
    else if (isolate(input$siblings2)==1){
      siblings12<-1}
    #calculates risk factor based on birth weight
    if (isolate(input$weight2)<2.5){
      weight2<-1
    } else {weight2 <-0}
    masterlist<- isolate(c(siblings22, siblings12, input$BD2, weight2, input$down_syndrome2,input$prematurity2, input$chd2, input$hiv2, input$sex2, input$smoking2))
    #under here match the masterlist to the row of the csv. Use the code in calculations.R
    row<-which(colSums(t(hos_rows) == masterlist) == ncol(hos_rows))
    hosest<- hos_results[row, "est"]
    isolate(paste(" 1.	该儿童RSV下呼吸道感染住院的风险是一般儿童的", round(hosest, digits=2), "倍"))
    
  })
  
  output$Res_hosProb2<- renderText({
    #copy the code from output$res_combiOR.hos
    req(input$action2)
    siblings22<-0
    siblings12<-0
    if (isolate(input$siblings2) == 2){
      siblings22<-1}
    else if (isolate(input$siblings2)==1){
      siblings12<-1}
    if (isolate(input$weight2)<2.5){
      weight2<-1
    } else {weight2 <-0}
    masterlist<- isolate(c(siblings22, siblings12, input$BD2, weight2, input$down_syndrome2,input$prematurity2, input$chd2, input$hiv2, input$sex2, input$smoking2))
    row<-which(colSums(t(prob_rows) == masterlist) == ncol(prob_rows))
    probest2<- prob_results[row, "est"]
    probest2<- probest2*100
    isolate(paste("2.	该儿童未来一年内发生RSV下呼吸道感染住院的可能性是百分之 ", round(probest2, digits = 2), "%"))
    
  })
  
  output$Res_CombiOR.poc2<-renderText({
    req(input$action2)
    #returns a list of the combination of the child's metrics, in line with the csv file
    calc_dob<-isolate(as.Date(input$dob))
    #calculates the difference in weeks between the child's dob and the current date
    diff_date<-difftime(todays_date, calc_dob, units= "weeks")
    diff_date <- as.numeric(diff_date)
    #6 months is 25 days 
    if (diff_date > 26){
      age2<-0
    } else {age2<-1}
    masterlist<-isolate(c(input$prematurity2, input$chd2, age2))
    row<-isolate(which(colSums(t(poc_rows) == masterlist) == ncol(poc_rows)))
    pocest<- isolate(poc_results[row, "est"])
    
    isolate(paste("3.	该儿童因RSV下呼吸道感染住院后发生不良结局的风险是一般儿童的   ", round(pocest, digits=2), "倍"))
    
  })
  
  output$resultsheader2<-renderText({
    #just to check that the combination list is correct
    #return(selected_var())
    req(input$action2)
    isolate(HTML(paste("<b>【RSV风险预测结果】<b>")))
  })
  
  output$preventionheader2<-renderText({
    #just to check that the combination list is correct
    #return(selected_var())
    req(input$action2)
    isolate(HTML(paste("<b>【如何预防RSV感染】<b>")))
  })
  
  output$prevention2<-renderText({
    req(input$action2)
    isolate(paste("目前暂无可用疫苗，国内单抗尚未上市。可通过加强个人防护等措施有效预防感染，包括在RSV好发的冬春季节，尽量避免去人群聚集场所，外出时规范佩戴口罩；注意手卫生，勤洗手，接触公共物品后不用手触碰眼、口、鼻；在儿童医院等医疗机构就诊要做好儿童个人防护，防止院内交叉感染。"))
  })
}
shinyApp(ui = ui, server = server)
