library(shiny)
library(shinydashboard)
#install.packages("shinyWidgets")
library(shinyWidgets)

todays_date <- as.Date(Sys.Date())

#read the csv files
hos <- read.csv("Res_CombiOR.hos.csv")
poc<- read.csv ("Res_CombiOR.poc.csv")
HosProb<- read.csv("Res_HosProb.csv")

#split the files into risk factors and results
hos_rows<- hos[c(1,2,3,4,5,6,7,8,9,10)]
hos_results<-hos[c(11,12,13)]

prob_rows<- HosProb[c(1,2,3,4,5,6,7,8,9,10)]
prob_results<-HosProb[c(11,12,13)]

poc_rows<- poc[c(1,2,3)]
poc_results<-poc[c(4,5,6)]

#User interface
ui <- fluidPage(
  #sets some styles and fonts for the application 
  tags$head(
    tags$img(src = "NJMU-1.png", height = "40px", width = "140px", style = "position:absolute;top:8px;left:15px;z-index:9999;"),
    tags$style(type="text/css", "label{  display: table-cell; text-align: left; vertical-align: middle;} .form-group { display: table; } #resultsheader{
                                 font-size: 16px;} #preventionheader{font-size: 16px;} #chinese{float:right;}")
  ),
  
  #this is to link the application to the new chinese page
  actionButton("chinese","Chinese（中文）", onclick = "window.open('https://uncover-livingreview.shinyapps.io/RSV_Chinese/')"),
  
  fluidRow(box(width =12, title="RSV RISK PREDICTION", solidHeader = TRUE, br(),
               tags$p(tags$b("[Instructions for use]"), br(),"Respiratory syncytial virus (RSV) is the most common pathogen identified in children under five years with acute lower respiratory infections (ALRI), accounting for about 30% of all respiratory pathogens and affecting children's health. The risk for hospitalisation with RSV-ALRI and poor outcomes after hospitalisation differs by individual. This tool, developed by a research team from Nanjing Medical University, aims to predict the risks associated with RSV-ALRI in children under five years in China.",br(),
                      "Please enter child’s information below. Based on the provided information, the tool can predict: ",br(),"1. The risk of hospitalisation for RSV-ALRI for the child;", br(), "2. The probability of hospitalisation for RSV-ALRI of the child within the next year;  ", br(), "3. The risk of poor outcomes (need for prolonged hospital stay, oxygen supplementation, mechanical ventilation, or ICU admission) after being hospitalisated for RSV-ALRI.",style = "font-size:16px;",br(),br() ))),
  fluidRow(
   
    box(width =12, tags$b("[Child's personal information]", style = "font-size:16px;"), br(),br(),
               #This is to make the values in line with the csv file. 1 means it is positive for risk factor, 0 means negative
               prettyRadioButtons("sex", "1. Sex: ", choices= list("  Male"=1,"  Female"=0), selected = 0, shape = "square", inline=T), 
               dateInput("dob", "2. Date of Birth:", width = "320px"), #need to figure out how to make this look better
               prettyRadioButtons("siblings", "3. Number of siblings (defined as those living together with the child):", choices= list("0"= 0, "1"=1, "≥2"=2), selected = 0, shape="square", inline=T),
               numericInput("weight", "4. Birthweight (kg):", value=0, min=0, max=20),
               prettyRadioButtons("prematurity", "5. Prematurity (i.e., gestational age < 37 weeks):", choices = list("Yes"=1, "No"=0), selected = 0, shape="square", inline= T),
               prettyRadioButtons("BD", "6. Bronchopulmonary dysplasia:", choices = list("Yes"=1, "No"=0), selected = 0, shape="square", inline= T),
               prettyRadioButtons("down_syndrome", "7. Down syndrome:", choices = list("Yes"=1, "No"=0),selected = 0, shape="square", inline= T),
               prettyRadioButtons("chd", "8. Congenital heart disease:", choices = list("Yes"=1, "No"=0), selected = 0, shape="square", inline= T),
               prettyRadioButtons("hiv", "9. HIV infection:", choices = list("Yes"=1, "No"=0), selected = 0, shape="square", inline= T),
               prettyRadioButtons("smoking", "10. Maternal smoking during pregnancy:", choices = list("Yes"=1, "No"=0), selected = 0, shape="square", inline= T)
               )),
  
  fluidRow(box(actionButton("action", "Submit"))),

  fluidRow(box(width =12, br(), tags$p( 
                  htmlOutput("resultsheader"),br(),
                  textOutput("res_combiOR.hos"), br(),
                  textOutput("Res_hosProb"), br(),
                  textOutput("Res_CombiOR.poc"), br(),
                  htmlOutput("preventionheader"),br(),
                  textOutput("prevention"), br(),
                  tags$b("[Disclaimer]", style = "font-size:16px;"),br(),
                  "All information contained and generated by this tool is only used for health education. This information should not be used in the diagnosis or treatment for any health issues or diseases, nor should it in any way replace clinical judgment or guidance for the treatment of individual patients."
                  
                  )))
  
  
               
)

#server
server <- function(input, output, session) {
  
  output$res_combiOR.hos <- renderText({
    #creates the 2 seperate variables from the siblings radio button
    req(input$action)
    siblings2<-0
    siblings1<-0
    if (isolate(input$siblings) == 2){
      siblings2<-1}
      else if (isolate(input$siblings)==1){
        siblings1<-1}
    #calculates risk factor based on birth weight
    if (isolate(input$weight)<2.5){
      weight<-1
    } else {weight <-0}
    masterlist<- isolate(c(siblings2, siblings1, input$BD, weight, input$down_syndrome,input$prematurity, input$chd, input$hiv, input$sex, input$smoking))
    #under here match the masterlist to the row of the csv. Use the code in calculations.R
    row<-which(colSums(t(hos_rows) == masterlist) == ncol(hos_rows))
    hosest<- hos_results[row, "est"]
    isolate(paste(" 1. The risk of hospitalisation for RSV-ALRI for the child would be ", round(hosest, digits=2), "times that of his/ her peers."))
    
    })
  
  output$Res_hosProb<- renderText({
    #copy the code from output$res_combiOR.hos
    req(input$action)
    siblings2<-0
    siblings1<-0
    if (isolate(input$siblings) == 2){
      siblings2<-1}
    else if (isolate(input$siblings)==1){
      siblings1<-1}
    if (isolate(input$weight)<2.5){
      weight<-1
    } else {weight <-0}
    masterlist<- isolate(c(siblings2, siblings1, input$BD, weight, input$down_syndrome,input$prematurity, input$chd, input$hiv, input$sex, input$smoking))
    row<-which(colSums(t(prob_rows) == masterlist) == ncol(prob_rows))
    probest<- prob_results[row, "est"]
    probest<- probest*100
    isolate(paste("2. The probability of hospitalisation for RSV-ALRI within the next year for the child would be  ", round(probest, digits = 2), "%"))
    
  })
  
  output$Res_CombiOR.poc<-renderText({
    req(input$action)
    #returns a list of the combination of the child's metrics, in line with the csv file
    calc_dob<-isolate(as.Date(input$dob))
    #calculates the difference in weeks between the child's dob and the current date
    diff_date<-difftime(todays_date, calc_dob, units= "weeks")
    diff_date <- as.numeric(diff_date)
    #6 months is 25 days 
    if (diff_date > 26){
      age<-0
    } else {age<-1}
    masterlist<-isolate(c(input$prematurity, input$chd, age))
    row<-isolate(which(colSums(t(poc_rows) == masterlist) == ncol(poc_rows)))
    pocest<- isolate(poc_results[row, "est"])
    
    isolate(paste("3. The risk of poor outcomes after being hospitalised for RSV-ALRI would be ", round(pocest, digits=2), "times that of his / her peers."))
    
  })
  
  output$resultsheader<-renderText({
    #just to check that the combination list is correct
    #return(selected_var())
    req(input$action)
    isolate(HTML(paste("<b>[Results]<b>")))
    })
  
  output$preventionheader<-renderText({
    #just to check that the combination list is correct
    #return(selected_var())
    req(input$action)
    isolate(HTML(paste("<b>[How to prevent RSV infection]<b>")))
  })
  
  output$prevention<-renderText({
    req(input$action)
    isolate(paste("To date, there are no vaccines for preventing RSV infection, and prophylactic monoclonal antibodies have not yet been marketed in China. Nonetheless, RSV infection can be effectively prevented by strengthening personal precautions, including avoiding visiting crowded places in winter and spring when RSV is most active and wearing masks at public venues; paying attention to hand hygiene, including washing hands frequently, and avoiding touching eyes, mouth, and nose with unwashed hands; and using personal protective equipment when attending hospitals to prevent hospital-acquired infections."))
  })
}


# Run the application 
shinyApp(ui = ui, server = server)


#notes and thoughts===========================
#  #lists<- renderPrint({
#masterlist<-as.list(selected_var())
#longlist<-sapply(masterlist,head,9)
#return(longlist)
#})

#label {
  #/* Other styling... */
    #text-align: right;
  #clear: both;
  #float:left;
  #margin-right:15px;
#}
